#!/usr/bin/env bash

DEFAULT_DOCKCROSS_IMAGE=dockcross/android-arm:latest

source $( cd "$( dirname "$0" )" >/dev/null && pwd )/dockcross-source

################################################################################
#
# This image is not intended to be run manually.
#
# To create a dockcross helper script for the
# dockcross/android-arm:latest image, run:
#
# docker run --rm dockcross/android-arm:latest > dockcross-android-arm-latest
# chmod +x dockcross-android-arm-latest
#
# You may then wish to move the dockcross script to your PATH.
#
################################################################################
