#!/usr/bin/env bash

DEFAULT_DOCKCROSS_IMAGE=dockcross/windows-arm64:latest

source $( cd "$( dirname "$0" )" >/dev/null && pwd )/dockcross-source

################################################################################
#
# This image is not intended to be run manually.
#
# To create a dockcross helper script for the
# dockcross/windows-arm64:latest image, run:
#
# docker run --rm dockcross/windows-arm64:latest > dockcross-windows-arm64-latest
# chmod +x dockcross-windows-arm64-latest
#
# You may then wish to move the dockcross script to your PATH.
#
################################################################################
