#!/usr/bin/env bash

DEFAULT_DOCKCROSS_IMAGE=dockcross/linux-armv7a-lts:latest

source $( cd "$( dirname "$0" )" >/dev/null && pwd )/dockcross-source

################################################################################
#
# This image is not intended to be run manually.
#
# To create a dockcross helper script for the
# dockcross/linux-armv7a-lts:latest image, run:
#
# docker run --rm dockcross/linux-armv7a-lts:latest > dockcross-linux-armv7a-lts-latest
# chmod +x dockcross-linux-armv7a-lts-latest
#
# You may then wish to move the dockcross script to your PATH.
#
################################################################################
